"""Export a TriMesh to common 3D file formats.

Supported formats:
  - Wavefront OBJ (.obj)  — widely supported, text-based
  - STL (.stl)            — common for 3D printing, ASCII variant
"""

from __future__ import annotations

from pathlib import Path

from .mesh import TriMesh


def export_obj(mesh: TriMesh, path: str | Path, comment: str = "") -> None:
    """Write the mesh as a Wavefront OBJ file.

    Parameters
    ----------
    mesh : TriMesh
        The mesh to export.
    path : str | Path
        Destination file path.
    comment : str
        Optional comment line written at the top of the file.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# Wavefront OBJ — generated by ascii_to_3d")
    if comment:
        lines.append(f"# {comment}")
    lines.append("")

    # Vertices
    for v in mesh.vertices:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")

    lines.append("")

    # Normals
    normals_written: dict[tuple[float, float, float], int] = {}
    normal_indices: list[int] = []
    for n in mesh.normals:
        key = (float(n[0]), float(n[1]), float(n[2]))
        if key not in normals_written:
            normals_written[key] = len(normals_written) + 1  # OBJ is 1-indexed
            lines.append(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}")
        normal_indices.append(normals_written[key])

    lines.append("")

    # Faces (1-indexed, with per-face normals)
    for fi, face in enumerate(mesh.faces):
        ni = normal_indices[fi] if fi < len(normal_indices) else 1
        v0, v1, v2 = face[0] + 1, face[1] + 1, face[2] + 1
        lines.append(f"f {v0}//{ni} {v1}//{ni} {v2}//{ni}")

    lines.append("")
    path.write_text("\n".join(lines))


def export_stl(mesh: TriMesh, path: str | Path, name: str = "ascii3d") -> None:
    """Write the mesh as an ASCII STL file.

    Parameters
    ----------
    mesh : TriMesh
        The mesh to export.
    path : str | Path
        Destination file path.
    name : str
        Solid name embedded in the STL header.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append(f"solid {name}")

    for fi, face in enumerate(mesh.faces):
        n = mesh.normals[fi] if fi < len(mesh.normals) else [0, 0, 0]
        lines.append(f"  facet normal {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}")
        lines.append("    outer loop")
        for vi in face:
            v = mesh.vertices[vi]
            lines.append(f"      vertex {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
        lines.append("    endloop")
        lines.append("  endfacet")

    lines.append(f"endsolid {name}")
    lines.append("")
    path.write_text("\n".join(lines))
